name: mjwarp
channels:
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.9.*=gpu_cuda128*
  - scipy
  - matplotlib
  - tqdm
  - pillow
  - pip
  - pip:
    - mujoco==3.8.0
    - mujoco-warp==3.8.0.1
    - warp-lang==1.12.1
    - glfw
    - pyopengl
